# Generated by Django 5.1.15 on 2026-03-21 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=512)),
                ('tipo', models.CharField(choices=[('portaria', 'Portaria'), ('resolucao', 'Resolução'), ('rod', 'ROD')], default='portaria', max_length=20)),
                ('caminho_arquivo', models.CharField(max_length=1024, unique=True)),
                ('indexado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ChunkDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_chunk', models.PositiveIntegerField()),
                ('conteudo', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documento')),
            ],
            options={
                'verbose_name': 'Chunk de Documento',
                'verbose_name_plural': 'Chunks de Documentos',
                'ordering': ['documento', 'numero_chunk'],
                'unique_together': {('documento', 'numero_chunk')},
            },
        ),
    ]
