# Generated by Django 5.2.13 on 2026-05-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_conversa_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='feedback',
            field=models.CharField(blank=True, choices=[('positive', 'Positivo'), ('negative', 'Negativo')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='foi_reformulada',
            field=models.BooleanField(default=False),
        ),
    ]
